BalanceOfSymbols:
	gcc -o BalanceOfSymbolsTest.out BalanceOfSymbolsTest.c BalanceOfSymbols.c ../../linkedListStack/LinkedListStack.c ../../../../linkedList/singlyLinkedList/SinglyLinkedList.c
	./BalanceOfSymbolsTest.out
	rm *.out
