ReverseQueue:
	gcc -o ReverseQueueTest.out ReverseQueueTest.c ReverseQueue.c ../linkedListQueue/LinkedListQueue.c ../../../linkedList/singlyLinkedList/SinglyLinkedList.c ../../stack/linkedListStack/LinkedListStack.c
	./ReverseQueueTest.out
	rm *.out
