InfixToPostfix:
	gcc -o InfixToPostfixTest.out InfixToPostfixTest.c InfixToPostfix.c ../../linkedListStack/LinkedListStack.c ../../../../linkedList/singlyLinkedList/SinglyLinkedList.c
	./InfixToPostfixTest.out
	rm *.out
